### ISSUE TITLE
Merge State list of portals

### ISSUE THREAD

**Issue by will-saunders** [sethvincent/nwdata.org#61]
I've been keeping an unofficial list of open data portals in WA for the last year or so:
https://kerika.com/m/wWFJ
I'd prefer to contribute to this project and drop my own.
Could you add my links to the directory?

**Comment by owy1** [comment]
which section of nwdata.org should this be under?

**Comment by will-saunders** [comment]
Ophelia –

How about just adding links to the Washington section?

Current:
Seattle

  *   data.seattle.gov<https://data.seattle.gov/>
  *   boundaries.seattle.io<http://boundaries.seattle.io/>

Proposed:

Seattle

  *   data.seattle.gov<https://data.seattle.gov/>
  *   boundaries.seattle.io<http://boundaries.seattle.io/>
  *   OpenBudget.Seattle.gov<https://openbudget.seattle.gov/>

Wilford “Will” Saunders | Open Data Guy
Washington State OCIO (WaTech<https://watech.wa.gov/>)
360.890-2580 m        |   360.40[7.8693] desk
Calendar<https://mobile.wa.gov/owa/calendar/will.saunders@watech.wa.gov/Calendar/calendar.html> |  SIP <sip:will.saunders@watech.wa.gov>  | Yammer <https://www.yammer.com/opendatainitiative/>  |  data.wa.gov<https://data.wa.gov/>

**Comment by owy1** [comment]
Hello Will, 
the following are already under Seattle section.  I'll put the OpenBudget under Seattle section as requested.  
*   data.seattle.gov<https://data.seattle.gov/>
*   boundaries.seattle.io<http://boundaries.seattle.io/>

are you going to be at meetup April 26?  
ophelia

**Comment by owy1** [comment]
please approve/merge PR#63

**Comment by owy1** [comment]
this issue is closed via PR#63
