### ISSUE TITLE
City of Washougal fiscal data site

### ISSUE THREAD

**Issue by will-saunders** [sethvincent/nwdata.org#62]
City of Washougal, WA has a fiscal transparency site:
https://washougalwa.opengov.com/transparency

**Comment by owy1** [comment]
which section would you like to put this?

**Comment by owy1** [comment]
how about under cites section: name: Washougal?

**Comment by sethvincent** [comment]
@owy1 that sounds good

**Comment by owy1** [comment]
please review/merge PR #64

**Comment by sethvincent** [comment]
merged #64, thanks!
